server.port=${PORT:8080}
# Thay localhost b\u1eb1ng link Neon th\u1ef1c t\u1ebf c\u1ee7a b\u1ea1n \u1edf ph\u1ea7n fallback sau d\u1ea5u hai ch\u1ea5m
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-bold-pond-ao82ebhx-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true