server.port=${PORT:8080}

# 1. \u0110\u01b0\u1eddng d\u1eabn URL tr\u1ecf th\u1eb3ng v\u1ec1 Neon (thay cho localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-bold-pond-ao82ebhx-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}

# 2. Username m\u1eb7c \u0111\u1ecbnh c\u1ee7a Neon
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}

# 3. M\u1eacT KH\u1ea8U TH\u1ef0C T\u1ebe: B\u1ea1n \u0111i\u1ec1n m\u1eadt kh\u1ea9u th\u1eadt c\u1ee7a b\u1ea1n b\u00ean Neon v\u00e0o ch\u1ed7 n\u00e0y nh\u00e9
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_wdjKX4q8FUlk}
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true